import type { Metadata } from "next";
import { Martian_Mono, Doto } from "next/font/google";
import "./globals.css";

const MonoFont = Martian_Mono({
  variable: "--font-azeret-mono",
  subsets: ["cyrillic"],
});

const DotoFont = Doto({
  variable: "--font-doto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${MonoFont.variable} ${DotoFont.variable} font-a-mono antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
